### ISSUE TITLE
UnboundLocalError: local variable 'x' referenced before assignment

### ISSUE THREAD

**Issue by atharvanvaidya** [dewanshrawat15/nptel-downloader#64]
**Describe the bug**
The script returns an UnboundLocalError when only the URL is given as an argument.

**To Reproduce**
1. python3 main.py -u https://nptel.ac.in/courses/106/106/106106211/

**Expected behavior**
The script should create Videos folder and download the videos with the given URL.

**Screenshots**
![Screenshot from 2020-10-02 10-06-29](https://user-images.githubusercontent.com/25866649/94888833-ea281400-0497-11eb-9c14-3050d791239d.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04
 - Browser: Firefox 
 - Version: Mozilla Firefox 66.0.3

**Comment by dewanshrawat15** [comment]
Merged :)
